### ISSUE TITLE
Latest Ninja version not importing script

### ISSUE THREAD

**Issue by Pietvw** [BitMEX/ninjatrader-bitmex#14]
Hi Ryan

I get the following error when importing the script into the latest version (8.0.13.0) of NT8.

"Ninjascript archive was made from an older incompatible version of NinjaTrader."

Is it possible to upload a new release built from the new version of NT8 please?

Regards,
Pieter

**Comment by ryanfox** [comment]
The plugin is only compatible with the indicated versions of NinjaTrader.

**Comment by Pietvw** [comment]
Hi Ryan

Where can I see which versions of Ninja is supported by the plugin?

**Comment by ryanfox** [comment]
8.0.0.10.
