### ISSUE TITLE
Volume does not update in real time

### ISSUE THREAD

**Issue by Auss1** [BitMEX/ninjatrader-bitmex#2]
It appears that the volume does not update in real time. All volume indicators remain at zero. When loading a chart it does show prior volume on volume indicators then does not update

**Comment by ryanfox** [comment]
This should work with the latest release. In a chart widget:
- Right click on the chart background, and select Indicators
- In the Available pane, scroll down to VOL
- Select VOL and click Add
- Click OK (returns you to the chart)

Adds current and past volumes to the bottom of the chart.

**Comment by Auss1** [comment]
Great! Working fine now thanks
