### ISSUE TITLE
Disconnects

### ISSUE THREAD

**Issue by mishaxz** [BitMEX/ninjatrader-bitmex#5]
I like using NinjaTrader with BitMex but it is not really usable due to not reconnecting after disconnects . I use a VPN so I don’t know if that happens for everyone or just VPN people. Sierra Chart has no such problems.

Usually it is good for a few hours before losing the connection.

The reason this is a big problem is because NT doesn't fill in the historical data that occured during the period of not being connected. And if you open a new chart, it won't have any historical data so you have to wait for things to fill in.

So really what would be nice is:

1. support for charting of historical data (including tick)
2. reconnection after disconnect (NT shows green but no data gets painted after reconnect)

**Comment by ryanfox** [comment]
Historical tick data is already supported. Reconnecting should work as of [v1.0.4.](https://github.com/BitMEX/ninjatrader-bitmex/releases/tag/v1.0.4)

**Comment by mishaxz** [comment]
great news!

**Comment by mishaxz** [comment]
btw. How can I enable historical tick data so that when I open ninjatrader it will draw it on the chart? currently (even after installing the new version and restarting), i see only ticks that occur after the program has been loaded on the tick or time based chart

**Comment by mishaxz** [comment]
also if I put my computer to sleep, and wake up - when it reconnects it is clearly visible that the reconnect did not load any historical data that occured while the computer was asleep
