### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Pete-the-viking** [BitMEX/ninjatrader-bitmex#8]
"Select the zip file downloaded in step 1"

What zip file, and what step 1??   There is no numerical numbers in the setup guide, and no metion of a zip file.

**Comment by ryanfox** [comment]
In the first installation step, you should have downloaded a release zip [here.](https://github.com/BitMEX/ninjatrader-bitmex/releases) The current one is [BitMEXConnect_v1.0.2.zip](https://github.com/BitMEX/ninjatrader-bitmex/releases/download/v1.0.2/BitMEXConnect_v1.0.2.zip)

The README should be a little clearer now.
